### ISSUE TITLE
Peers connections lost on Telestai Wallet 2.1.4 and 2.1.5

### ISSUE THREAD

**Issue by EKLETTICKCRYPTO** [Telestai-Project/telestai#4]
Hi guys I found an issue on the wallet , after adding the nodes from the node list on https://telestai.cryptoscope.io/network/
seems some of them pop on and off from peer list , and just one or two have stable connection to the wallet.
Attached I leave my wallet debug file

[debug.log](https://github.com/user-attachments/files/16652548/debug.log)

**Comment by zachchan105** [comment]
Resolved in PR https://github.com/Telestai-Project/telestai/pull/3
Peer stability should be a lot better in v2.1.6 which is going to be released shortly
